name: ReMap
main: com.kiwhen.remap.Main
version: 0.2
author: kiwhen
website: http://www.kiwhen.com
depend: [ProtocolLib]
commands:
  remap:
    description: Various functions. Type "/remap" to see.
    usage: Type "/remap" to see a list of commands.